Repository nodejs/security-wg, pull requests merged in 2018-06, with the labels that each got.

#290 vuln(NSWG-ECO-439): serve
  vuln/npm/439.json
Labels: vulnerabilities

#283 vuln(NSWG-ECO-437): sexstatic
  vuln/npm/437.json
Labels: vulnerabilities

#291 vuln(NSWG-ECO-438): update CVE
  vuln/npm/438.json
Labels: vulnerabilities

#297 vuln(NSWG-ECO-440): express-cart
  vuln/npm/440.json
Labels: vulnerabilities

#201 doc: added entries for March 2018 core vulnerabilities
  vuln/core/46.json
  vuln/core/47.json
  vuln/core/48.json
Labels: vulnerabilities

#307 doc: add entries for June vulns
  vuln/core/49.json
  vuln/core/50.json
  vuln/core/51.json
  vuln/core/52.json
Labels: vulnerabilities

#318 vuln(NSWG-ECO-442): git-dummy-commit
  vuln/npm/442.json
Labels: vulnerabilities

#305 docs(processes): security team offboarding
  processes/security_team_offboarding.md
Labels: security-wg-agenda

#312 Add Alex Knol to Security WG / Triage team
  README.md
  processes/third_party_vuln_process.md
Labels: member

#325 vuln(NSWG-ECO-448): memjs
  vuln/npm/448.json
Labels: vulnerabilities

#328 vuln(NSWG-ECO-449): buttle
  vuln/npm/449.json
Labels: vulnerabilities
