Repository nodejs/security-wg, pull requests merged in 2018-09, with the labels that each got.

#396 vuln(NSWG-ECO-465): samsung-remote
  vuln/npm/465.json
Labels: vulnerabilities

#395 vuln(NSWG-ECO-464): exceljs
  vuln/npm/464.json
Labels: vulnerabilities

#347 NSWG-ECO-451 - NSWG-ECO-453
  vuln/npm/467.json
  vuln/npm/468.json
  vuln/npm/469.json
Labels: vulnerabilities

#401 vuln(NSWG-ECO-471): ascii-art
  vuln/npm/471.json
Labels: vulnerabilities

#400 vuln(NSWG-ECO-470): ps
  vuln/npm/470.json
Labels: vulnerabilities

#407 Fix some typos in the readme
  README.md
Labels: DOCS

#406 add Andreas to triage team
  processes/third_party_vuln_process.md
Labels: member
