Repository nodejs/security-wg, pull requests merged in 2018-08, with the labels that each got.

#234 nswg-reporter: initial proposition for hackerone reporter
  package-lock.json
  package.json
  tools/README.md
  tools/reporter/CliPrompt.js
  tools/reporter/HackerOneClient.js
  tools/reporter/NswgLinter.js
  tools/reporter/NswgReporter.js
  tools/reporter/cli.js
  tools/reporter/config.js
  tools/reporter/index.js
Labels: enhancement

#361 feat(nswg-reporter): use rich user object for reports
  tools/reporter/NswgReporter.js
Labels: enhancement

#360 vuln(NSWG-ECO-456): add cve
  vuln/npm/456.json
Labels: vulnerabilities

#372 Added aedes vuln
  vuln/npm/457.json
Labels: vulnerabilities

#373 vuln(NSWG-ECO-457): add cve
  vuln/npm/457.json
Labels: vulnerabilities

#378 add vulns NSWG-ECO-458 and 459
  vuln/npm/458.json
  vuln/npm/459.json
Labels: vulnerabilities

#379 vuln(NSWG-ECO-460): flintcms
  vuln/npm/460.json
Labels: vulnerabilities

#380 vuln(NSWG-ECO-461): cryo
  vuln/npm/461.json
Labels: vulnerabilities

#385 vuln(NSWG-ECO-460): add cve
  vuln/npm/460.json
Labels: vulnerabilities

#384 vuln(NSWG-ECO-461): add cve
  vuln/npm/461.json
Labels: vulnerabilities

#383 vuln(NSWG-ECO-442): add cve
  vuln/npm/442.json
Labels: vulnerabilities

#381 vuln(NSWG-ECO-462): git-dummy-commit
  vuln/npm/462.json
Labels: vulnerabilities

#388 vuln(NSWG-ECO-442): remove duplicate report
  vuln/npm/442.json
  vuln/npm/462.json
Labels: vulnerabilities

#391 Add support for pulling CVE IDs for a report from the HackerOne API
  tools/reporter/HackerOneClient.js
  tools/reporter/NswgReporter.js
Labels: enhancement

#386 vuln(NSWG-ECO-463): egg-scripts
  vuln/npm/463.json
Labels: vulnerabilities

#362 Process for recognizing work
  processes/recognition.md
Labels: process

#351 Establishing information for the vuln db
  README.md
  processes/vuln_db.md
Labels: process
