Repository nodejs/security-wg, pull requests merged in 2018-03, with the labels that each got.

#142 vuln: XSS in mrk.js
  vuln/npm/382.json
Labels: vulnerabilities

#132 vuln(CVE-2018-3729): localhost-now path traversal
  vuln/npm/377.json
Labels: vulnerabilities

#133 vuln(CVE-2018-3727): 626 path traversal
  vuln/npm/378.json
Labels: vulnerabilities

#134 vuln(CVE-2018-3717): anywhere xss
  vuln/npm/379.json
Labels: vulnerabilities

#135 vuln(CVE-2018-3716): simplehttpserver xss
  vuln/npm/380.json
Labels: vulnerabilities

#136 vuln(CVE-2018-3725): hekto path traversal
  vuln/npm/381.json
Labels: vulnerabilities

#144 vuln(CVE-2018-3713): [angular-http-server] Path Traversal
  vuln/npm/384.json
Labels: vulnerabilities

#149 vuln(CVE-2018-3734): stattic path traversal
  vuln/npm/386.json
Labels: vulnerabilities

#145 vuln(CVE-2018-3715): glance path traversal
  vuln/npm/385.json
Labels: vulnerabilities

#152 vuln(CVE-2018-3714): node-srv path traversal
  vuln/npm/383.json
Labels: vulnerabilities

#158 dgonzalez into the security working group
  README.md
Labels: member

#153 vuln(CVE-2018-3724): general-file-server path traversal
  vuln/npm/387.json
Labels: vulnerabilities

#160 vuln(CVE-2018-3718): serve
  vuln/npm/389.json
Labels: vulnerabilities

#155 feat(3rd-triage-team): Add @dgonzalez to the triage team
  processes/third_party_vuln_process.md
Labels: member

#162 vuln(CVE-2018-3717): simple-server
  vuln/npm/390.json
Labels: vulnerabilities

#166 Add Marcin Hoppe to the Security WG
  README.md
Labels: member

#167 Add Marcin Hoppe to the triage team
  processes/third_party_vuln_process.md
Labels: member, wip

#179 Fix NSWG-ECO-330 affected range and add CVE info
  vuln/npm/330.json
Labels: vulnerabilities

#178 Fix version ranges in NSWG-ECO-332
  vuln/npm/332.json
Labels: vulnerabilities

#184 Fix dates in NSWG-ECO-391 --- NSWG-ECO-393
  vuln/npm/391.json
  vuln/npm/392.json
  vuln/npm/393.json
Labels: vulnerabilities

#185 Fix NSWG-ECO-393 publish date
  vuln/npm/393.json
Labels: vulnerabilities

#187 vuln: disclose openwhisk memory exposure vuln
  vuln/npm/395.json
Labels: vulnerabilities

#186 vuln: historic mongoose memory exposure vuln
  vuln/npm/394.json
Labels: vulnerabilities

#193 Fix another date mistype in npm/391-395
  vuln/npm/391.json
  vuln/npm/392.json
  vuln/npm/393.json
  vuln/npm/394.json
  vuln/npm/395.json
Labels: vulnerabilities

#191 Fix NSWG-ECO-332 CVEs list
  vuln/npm/332.json
Labels: vulnerabilities

#192 Fix markdown lists syntax in references
  vuln/npm/373.json
  vuln/npm/374.json
  vuln/npm/375.json
  vuln/npm/376.json
  vuln/npm/377.json
  vuln/npm/378.json
  vuln/npm/379.json
  vuln/npm/380.json
  vuln/npm/381.json
  vuln/npm/382.json
  vuln/npm/383.json
  vuln/npm/384.json
  vuln/npm/385.json
  vuln/npm/386.json
Labels: vulnerabilities

#189 vuln: disclose mysql memory exposure vuln
  vuln/npm/397.json
Labels: vulnerabilities

#180 Fix NSWG-ECO-85 affected range
  vuln/npm/85.json
Labels: vulnerabilities

#181 Fix NSWG-ECO-328 affected range
  vuln/npm/328.json
Labels: vulnerabilities
